# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  laravel-course-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: laravel-course-mysql
    volumes:
      - laravel-course-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=laravel-course
      - MYSQL_DATABASE=laravel-course
      - MYSQL_USER=laravel-course
      - MYSQL_PASSWORD=laravel-course
  app:
    image: ambientum/php:7.2-nginx
    container_name: laravel-course-app
    environment:
      XDEBUG_ENABLED: "true"
      XDEBUG_CONFIG: remote_host=192.168.15.15
      PHP_IDE_CONFIG: serverName=PHPSTORM
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql

